### PR TITLE
Fix 4chan X

### PR DESCRIPTION
**Pull request by seaweedchan**

### CODE REVIEW

**Comment by ihavenoface** [comment]
Thank you.

**Comment by seaweedchan** [comment]
It didn't carry over the tags like I feared so only your master version is updated right now.

**Comment by ihavenoface** [comment]
I'll just add you to the collaborator list if you want.

> Note to self: WP7.5 is a true pain - don't buy it.

**Comment by seaweedchan** [comment]
Alright its all good to go now.

**Comment by ihavenoface** [comment]
Thanks again.
Do you want to stay on there, or?

**Comment by seaweedchan** [comment]
I don't mind either way. I won't be using your fork because I like the increasing thread updater but I don't mind helping out with it.

Do you want me to auto-disable the 4chan extension in your fork? AppChan X and OneeChan does that, but Mayhem doesn't want to in his fork because people might want specific features like YouTube embedding.

**Comment by ihavenoface** [comment]
Didn't even read the changelog of that thing yet.
Generally I like the idea of being able to choose, so asking before disabling certain features would be nice.
For now disabling them is fine, I guess, since alternatives (such as YTL) are already linked on the gh-pages.

**Comment by seaweedchan** [comment]
How about a new option to auto-disable it, turned on by default. That would feel kind of redundant though.

**Comment by ihavenoface** [comment]
The new option sounds fine for now.

**Pull request merged**
