### PR TITLE
Update for new 4chan post success page

### PR DESCRIPTION
**Pull request by MacilPrime**
4chan tweaked its 'post successful' screen, moving the comment that has the new post ID to be a child of the <body> element. This makes 4chan X interpret it correctly.

### CODE REVIEW

**Comment by ihavenoface** [comment]
> if body then true

Are you sure you want to do this?

**Comment by MacilPrime** [comment]
```
    else unless msg = $ 'body', doc
      err = 'Connection error with sys.4chan.org.'
```

Execution falls into that block only if the body element is missing, which I imagine should only be on a connection problem. (Before, it would go into that block if the b element was missing, which I'm also pretty sure would only be due to connection problems.)

```
    [_, threadID, postID] = msg.lastChild.textContent.match /thread:(\d+),no:(\d+)/
```

And then `msg` is only ever accessed here, where its last element is grabbed and checked for the thread and post IDs.

Since the comment with the IDs was moved up out of the message element and into the body element, we need to check the last child of the body element instead of the last child of the message element. (And semi-related, the message element was changed from being a `b` tag to `h1` tag, but we don't even use it any more now here.)

**Comment by MacilPrime** [comment]
Seems like mayhem pushed his fix just recently. Functionally similar, though it also checks the post page title which is probably a better check than what used to be in there.
https://github.com/MayhemYDG/4chan-x/commit/b6645773f32ddd841a33b398c7952db702fcd0c2

**Comment by ihavenoface** [comment]
Merged with 4925d584a0e0488a3778fe5f60ac763be1c2d204.
Thank you nonetheless.

**Pull request closed without merging**
