### PR TITLE
Youtube Embedding with Linkification

### PR DESCRIPTION
**Pull request by zixaphir**

### CODE REVIEW

**Comment by ihavenoface** [comment]
> slapping an iframe on the site

While I like the idea of being able to choose what gets embedded this solution still doesn't beat http://userscripts.org/scripts/show/83584.
How about a possibility to close this thing again?

**Comment by zixaphir** [comment]
Maybe.

**Comment by seaweedchan** [comment]
Slapping an iframe on the site is exactly what Youtube Link Title does....

**Comment by ihavenoface** [comment]
YTL places an iframe on the site.

**Comment by seaweedchan** [comment]
You said you took issue with Zixaphir's version "slapping an iframe on the site" and linked to http://userscripts.org/scripts/show/83584 which does _exactly_ that.

**Comment by ihavenoface** [comment]
Right.

Anyway. Thanks.

**Pull request closed without merging**
